### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by voveson** [skydiver/october-plugin-ssologin#3]
I am seeing the following error when attempting to login with Google:

![screen shot 2017-07-05 at 3 32 59 pm](https://user-images.githubusercontent.com/6799654/27885973-4c792aba-6197-11e7-89fc-c28dc85e20cf.png)

I believe I have followed all of the necessary steps to setup the plugin.  Any idea why this error is being thrown?  Thanks!

**Comment by voveson** [comment]
Further, commenting out lines 123-127 of `vendor/firebase/php-jwt/src/JWT.php`:
```php
//  if (isset($payload->iat) && $payload->iat > ($timestamp + static::$leeway)) {
//    throw new BeforeValidException(
//      'Cannot handle token prior to ' . date(DateTime::ISO8601, $payload->iat)
//    );
//  }
```
Eliminates the issue, but I'm not sure why, or what those lines are meant to do.

**Comment by petehalverson** [comment]
@voveson, check your server's clock. https://github.com/firebase/php-jwt/issues/42

**Comment by voveson** [comment]
Thanks @petehalverson , that fixed my issue!
